### ISSUE TITLE
Inline Quotes

### ISSUE THREAD

**Issue by kingrpaul** [kingrpaul/captain-charles-johnson_a-general-history-of-the-pyrates#13]
chapter-4
In “The Lord Chief Justices’ Speech” the inline quotes can be `<q>` (not `<em>`)
 @robinwhittleton

**Comment by kingrpaul** [comment]
@robinwhittleton: 
I'd misinterpreted this as `<em>` == "judge pounds table with fist", but lots of italics and I see that it was meant to indicate a quote. 
If I substitute `<q>` for `<em>` in these cases, there are no italics. SEMOS only talks about `<q>` being used for speaker thoughts.  I've instead used single quotes to indicate this quote within a block quote. 
Good?
789b8c55f9eaf68f9e3554646068272fe09c4e67

**Comment by robinwhittleton** [comment]
Yep, that looks fine to me.
