### ISSUE TITLE
Tables v. Lists

### ISSUE THREAD

**Issue by kingrpaul** [kingrpaul/captain-charles-johnson_a-general-history-of-the-pyrates#16]
chapter-11
There are several lists (e.g. ”Prisoners Taken in the Ranger”, “The following pirates were executed”) that should be tables, not lists. rowspan attributes can be used to make cells apply to multiple rows.
When this is changed we can remove the margin-top rule from .person in the CSS
chapter-15
List prefaced by “Robert Auchmuta” should be a table too
@robinwhittleton

**Comment by kingrpaul** [comment]
@robinwhittleton: Many of the lists in the text began as tables. Used rowspans, and other approaches, but as tables they rendered quite poorly in ebook form. As lists, the content, meaning, and relationships are maintained, but also readability.  I tried many approaches and put a good deal of effort into trying to make these work well as tables.

**Comment by robinwhittleton** [comment]
I know what you’re saying, but I still think I disagree. I’ve tested a converting the _Ranger_ example into a table and yes, it renders pretty badly at a standard font size. But dropping the font size for particular tables, and playing with the alignment makes it more usable, and the tabular structure makes it more accessible too.

But regardless, it’s your production, so I’ll leave the final choice to you.

**Comment by kingrpaul** [comment]
@robinwhittleton
I appreciate that and did want to retain the the look of the hand-drawn table, as much as possible, including trying to include the curly-braces. But, words broke badly between lines, column widths behave badly, and if I do things in CSS that get it to work on the webpage, it falls apart on rendering to an ebook. 

There are two other things I wanted to mention, though:

(1) If you look at chapter-17 lines 77-113, there are “last words” presented as a table, drama, where the 
“together” class seems to fit really well. But, in ebook form the “persona” gets broken up awkwardly, 
e.g.

OF BOTH
TOGETH
ER

I don’t see a way to prevent this and decided it was tolerable. If you have any insight on how it might be improved, I’d much appreciate.


Also, 
(2) In two cases, to pick out certain data from the lists, I used :not() in local.css. Elements that are siblings of this but are not that. Whenever I clean the manuscript, clean add a space before the colon which doesn’t show up on lint, but does break the build. It’s obscure, but I think it’s a bug in clean. Not sure if that’s something that should be reported, or ignored. (I have a similar, but unrelated issue in the Blackwood project.)

**Comment by robinwhittleton** [comment]
1. I can’t replicate that. Where are you seeing it?
2. Typically we avoid `:not()` in ebooks as support is spotty, and we don’t handle conversion in the non-advanced epubs. But there are other options. For lines 71-72 you can replace `table:not([epub|type~="z3998:drama"])` with `#the-trials-of-the-pirates > table`. And for `.name-age ~ li:not(.place):not(.name-age)`, it only seems to apply to three nodes in chapter-15 that all deal with a legal finding, so I’d just add a class for them and target that instead.

**Comment by kingrpaul** [comment]
Sorry for the confusion. Those are separate questions. Use of `:not() ` produces good results except that it elicits a small error from clean. Not a problem for me to work around.

The drama issue is unrelated, and I just see it that in that one segment of drama. the personae get broken awkwardly in some cases. Unless you'd like me to wrap "separately" and "together" in `<small>` tags, maybe it's best to leave it be.

**Comment by robinwhittleton** [comment]
Let’s leave the drama issue be, as I can’t replicate it.

**Comment by acabal** [comment]
I'm looking at this tables vs lists issue and it seems to me that they should definitely be tables, both semantically and in display. They were tables originally in print and it is clearly tabular data being presented. I think they will also be much more readable once we remove the small caps and format them normally.

It's true that some might be too wide for certain sizes of ereader; you can try using media queries to reformat table rows for smaller screens. Of course this won't work on bad ereaders like Kindle, but maybe some day Kindle will figure itself out and the correctly-formatted code we wrote today will start working correctly for free. And media queries/tables *do* work nicely today (with horizontal scrolling, etc.) on many ereaders like Kobo and iBooks.

This will also help clean up some of the more complicated selectors because you can select on tfoot.

**Comment by kingrpaul** [comment]
I won't be able to see it on Kobo or Apple; just Lithium or Kindle reader on Galaxy Note (which I don't think of as small), Kindle Fire, or Calibre Reader. 
The small caps were to help convey  the structure of the data, make it easy to read. The selectors are as simple as I could made them, based on the content and format.  One thing I considered but didn't try was to fix the relative cell sizes to the proportions they appeared on the page and use ellipsis for text overflow. Maybe that's the answer. 
This will take time, as each approach so far has.

**Comment by acabal** [comment]
I don't think we have to worry too much about how the table will look on different ereaders. There's tons of ebooks in the catalog that have wide, detailed tables that almost certainly don't look great on older ereaders or tiny screens. How the renderer handles them is up to it and we can't really try to please every single one. 

If you structure your table correctly, perhaps media queries might allow you to reformat them for smaller screens. However wide tables on small screens is not really a solved problem on the modern web, let alone in ebooks. Most solutions rely on JS which we can't do.

Just make them tables like they are in print, using basic table formatting. That's all that's necessary here.

**Comment by kingrpaul** [comment]
57d89404f5632762dbd576111df7b7a48e64c6c8
